development:
  adapter: postgresql
  encoding: unicode
  database: sinix_development
  host: localhost
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: sinix_production
